### ISSUE TITLE
Expected training code release

### ISSUE THREAD

**Issue by akshitac8** [Alibaba-MIIL/ZS_SDL#1]
Hello @ebenbaruch,

Congratulations on your paper acceptance. I wanted to ask, when are you planning to release the training code?

Thanks,
Akshita

**Comment by ebenbaruch** [comment]
hey Akshita,

Thanks for your kind words,
We do plan to publish the training code as soon as possible. There is some delay due to commercial issues.

Best regards, 
Emanuel

**Comment by strawberry2020** [comment]
Waiting for the training code.

**Comment by strawberry2020** [comment]
Looking forward to the released training code!

**Comment by ebenbaruch** [comment]
The training code is now available:
https://github.com/Alibaba-MIIL/ZS_SDL#training-code

@akshitac8, @strawberry2020
